import { useEffect, useMemo, useState } from 'react'
import { LanguageContext } from './useLanguage'

const translations = {
  en: {
    'Смартфони': 'Smartphones',
    'Преміальні мобільні пристрої для роботи та відпочинку': 'Premium mobile devices for work and play',
    'Ноутбуки': 'Laptops',
    'Потужні ноутбуки для роботи, навчання та ігор': 'Powerful laptops for work, study, and gaming',
    'Планшети': 'Tablets',
    'Мобільні пристрої для творчості та продуктивності': 'Mobile devices for creativity and productivity',
    'ПК': 'Desktop PCs',
    'Системні блоки для будь-яких задач': 'Desktop computers for every task',
    'Монітори': 'Monitors',
    'Яскраві дисплеї для роботи та ігор': 'Vivid displays for work and gaming',
    'Відеокарти': 'Graphics cards',
    'Графічні карти для високої продуктивності': 'Graphics cards built for high performance',
    'Процесори': 'Processors',
    'Серця сучасних комп’ютерів': 'The heart of modern computers',
    'Материнські плати': 'Motherboards',
    'Надійна основа для збірки': 'A reliable foundation for your build',
    'Оперативна пам’ять': 'Memory',
    'Швидкість і стабільність системи': 'Speed and stability for your system',
    'SSD/HDD': 'SSD/HDD drives',
    'Сховище даних для повного набору': 'Storage to complete your setup',
    'Клавіатури': 'Keyboards',
    'Комфортне введення тексту та управління': 'Comfortable typing and control',
    'Миші': 'Mice',
    'Точність для роботи та геймінгу': 'Precision for work and gaming',
    'Навушники': 'Headphones',
    'Звуковий комфорт і якість': 'Comfort and high-quality sound',
    'Аксесуари': 'Accessories',
    'Корисні доповнення для техніки': 'Useful add-ons for your devices',
    'Інша цифрова техніка': 'Other digital tech',
    'Різноманітні гаджети й аксесуари': 'A range of gadgets and accessories',
    'Київ': 'Kyiv',
    'Львів': 'Lviv',
    'Одеса': 'Odesa',
    'Новий': 'New',
    'В обробці': 'Processing',
    'Відправлено': 'Shipped',
    'Доставлено': 'Delivered',
    'Скасовано': 'Canceled',
    'Чорний': 'Black',
    'Смартфон із титановим корпусом, потужним чіпом A17 Pro і професійною камерою ProRaw.': 'A smartphone with a titanium body, the powerful A17 Pro chip, and a professional ProRAW camera.',
    'Флагманський смартфон з S Pen, потужним процесором та кращою камерою для контенту.': 'A flagship smartphone with an S Pen, a powerful processor, and an advanced camera for content creation.',
    'Комфортний геймерський ноутбук із потужним Ryzen 9 і компактним корпусом.': 'A comfortable gaming laptop with a powerful Ryzen 9 processor in a compact body.',
    'Компактний ультрабук із бездоганною якістю зборки для щоденної продуктивності.': 'A compact ultrabook with excellent build quality for everyday productivity.',
    'Планшет для творчості, відео та професійної роботи з потужним M2 чіпом.': 'A tablet for creative work, video, and professional tasks, powered by the M2 chip.',
    'Потужна відеокарта для ігор в 4K із високою частотою кадрів та плавністю.': 'A powerful graphics card for smooth 4K gaming with high frame rates.',
    'Преміальні навушники з чудовою шумоізоляцією, якість звуку і комфортом на весь день.': 'Premium headphones with excellent noise cancellation, sound quality, and all-day comfort.',
    'Геймерська миша з точним датчиком, легендарним дизайном та кастомізацією під стиль гри.': 'A gaming mouse with a precise sensor, iconic design, and settings tailored to your play style.',
    '27-дюймовий ігровий монітор із швидкою реакцією, високою чіткістю та плавним OLED-екраном.': 'A 27-inch gaming monitor with fast response, sharp detail, and a smooth OLED display.',
    'Модуль оперативної пам’яті DDR5 з високою швидкістю та стабільною роботою.': 'A DDR5 memory kit delivering high speed and stable performance.',
    'Швидкий SSD для системи, ігор і роботи з великими файлами.': 'A fast SSD for your operating system, games, and large files.',
    'Механічна клавіатура для продуктивної роботи та ігор із RGB-підсвічуванням.': 'A mechanical keyboard for productive work and gaming, featuring RGB lighting.',
    'Відмінна якість, швидка доставка і все як обіцяли.': 'Excellent quality, fast delivery, and everything as promised.',
    'Дуже зручно в користуванні. Гарна батарея і чіткий дисплей.': 'Very easy to use, with a great battery and a sharp display.',
    'Супер сервіс і все працює без нарікань.': 'Great service, and everything works as expected.',
    'Рекомендуємо. Відмінний вибір і хороший дизайн.': 'Recommended. A great selection and a clean design.',
    'ГБ': 'GB',
    'ТБ': 'TB',
    'МП': 'MP',
    'мА·г': 'mAh',
    'Вт·год': 'Wh',
    'год': 'hours',
    'г': 'g',
    'кнопок': 'buttons',
    'Гц': 'Hz',
    'memory': 'Memory',
    'ram': 'RAM',
    'display': 'Display',
    'camera': 'Camera',
    'battery': 'Battery',
    'os': 'Operating system',
    'cpu': 'CPU',
    'ssd': 'SSD',
    'gpu': 'GPU',
    'resolution': 'Resolution',
    'type': 'Type',
    'interface': 'Interface',
    'power': 'Power',
    'brand': 'Brand',
    'color': 'Color',
    'sensors': 'Sensor',
    'buttons': 'Buttons',
    'weight': 'Weight',
    'connection': 'Connection',
    'diagonal': 'Size',
    'refreshRate': 'Refresh rate',
    'panel': 'Panel',
    'capacity': 'Capacity',
    'speed': 'Speed',
    'format': 'Format',
    'kit': 'Kit',
    'read': 'Read speed',
    'layout': 'Layout',
    'switches': 'Switches',
    'lighting': 'Lighting',
  },
  uk: {
    Home: 'Головна',
    Catalog: 'Каталог',
    Categories: 'Категорії',
    About: 'Про нас',
    Contacts: 'Контакти',
    Search: 'Пошук',
    Favorites: 'Обране',
    Cart: 'Кошик',
    Dark: 'Темна',
    Light: 'Світла',
    Admin: 'Адмін',
    User: 'Користувач',
    'My products': 'Мої товари',
    Logout: 'Вийти',
    Login: 'Увійти',
    Register: 'Зареєструватися',
    Company: 'Компанія',
    Support: 'Підтримка',
    Contact: 'Зв’язок',
    'Help center': 'Центр допомоги',
    Shipping: 'Доставка',
    Returns: 'Повернення',
    'About us': 'Про нас',
    'Marketplace for everyday upgrades crafted for modern digital living.': 'Майданчик корисних товарів для сучасного цифрового життя.',
    'Main navigation': 'Головна навігація',
    'Language switcher': 'Перемикач мови',
    'Toggle favorite': 'Додати до обраного',
    'New season drop': 'Новинки сезону',
    'Smart shopping for the next wave of living.': 'Розумні покупки для нового рівня життя.',
    'Explore premium essentials, tech finds, and home upgrades curated for modern life.': 'Добірка преміальних товарів, техніки та корисних речей для сучасного життя.',
    'Shop now': 'До покупок',
    'Explore categories': 'Переглянути категорії',
    'happy buyers': 'задоволених покупців',
    'new arrivals': 'нових надходжень',
    'average rating': 'середня оцінка',
    'Top seller': 'Лідер продажів',
    'Popular categories': 'Популярні категорії',
    'View all': 'Переглянути всі',
    'Featured products': 'Рекомендовані товари',
    'New arrivals': 'Новинки',
    'Popular this week': 'Популярне цього тижня',
    'Flash deal': 'Гаряча пропозиція',
    'Mid-season sale': 'Розпродаж середини сезону',
    'Up to 50% off on selected gear and accessories for a smarter setup.': 'Знижки до 50% на вибрану техніку та аксесуари для вашого робочого місця.',
    'Claim offer': 'Скористатися пропозицією',
    'Why choose us': 'Чому обирають нас',
    'Built for better buying decisions.': 'Допомагаємо обирати краще.',
    'Curated quality': 'Перевірена якість',
    'Only trusted brands and products selected for long-term value.': 'Лише надійні бренди й товари, що служать довго.',
    'Fast delivery': 'Швидка доставка',
    'Tracked shipping and quick dispatch across the country.': 'Відстеження посилок і швидка відправка по всій країні.',
    'Secure checkout': 'Безпечна оплата',
    'Protected payments, easy returns, and clear order tracking.': 'Захищені платежі, просте повернення та відстеження замовлень.',
    'Browse digital essentials': 'Техніка та цифрові товари',
    Explore: 'Переглянути',
    'All gadgets and gear': 'Усі гаджети й техніка',
    Category: 'Категорія',
    'All categories': 'Усі категорії',
    Brand: 'Бренд',
    'Any brand': 'Будь-який бренд',
    Price: 'Ціна',
    Min: 'Мін.',
    Max: 'Макс.',
    Rating: 'Оцінка',
    'All ratings': 'Усі оцінки',
    Availability: 'Наявність',
    Any: 'Будь-яка',
    'In stock': 'В наявності',
    Limited: 'Обмежена кількість',
    'products found': 'товарів знайдено',
    Featured: 'Рекомендовані',
    'Price: low to high': 'Ціна: від низької до високої',
    'Price: high to low': 'Ціна: від високої до низької',
    'Top rated': 'Найвищий рейтинг',
    Grid: 'Сітка',
    List: 'Список',
    'No products match your search. Try another filter.': 'За вашим запитом нічого не знайдено. Спробуйте інші фільтри.',
    'Search products': 'Пошук товарів',
    'Your shopping cart': 'Ваш кошик',
    Remove: 'Видалити',
    'Order summary': 'Підсумок замовлення',
    Subtotal: 'Проміжний підсумок',
    Total: 'Разом',
    'Proceed to checkout': 'Перейти до оформлення',
    'Your cart is empty': 'Ваш кошик порожній',
    'Add a few products and come back.': 'Додайте товари до кошика, щоб продовжити.',
    'Browse catalog': 'Перейти до каталогу',
    'Your saved items': 'Збережені товари',
    'No favorites yet': 'Поки немає обраного',
    'Save products you like to compare and buy later.': 'Зберігайте товари, щоб порівняти їх і придбати пізніше.',
    'Add to cart': 'До кошика',
    View: 'Переглянути',
    New: 'Новинка',
    Checkout: 'Оформлення замовлення',
    'Complete your order': 'Завершіть оформлення замовлення',
    'First name': 'Ім’я',
    'Last name': 'Прізвище',
    Email: 'Електронна пошта',
    Phone: 'Телефон',
    City: 'Місто',
    Address: 'Адреса',
    'Delivery method': 'Спосіб доставки',
    'Courier delivery': 'Кур’єрська доставка',
    Pickup: 'Самовивіз',
    'Payment method': 'Спосіб оплати',
    Card: 'Картка',
    'Cash on delivery': 'Оплата при отриманні',
    'Digital wallet': 'Цифровий гаманець',
    'Place order': 'Оформити замовлення',
    'Your cart is empty.': 'Ваш кошик порожній.',
    Delivery: 'Доставка',
    'Back to cart': 'Повернутися до кошика',
    'Product not found.': 'Товар не знайдено.',
    'Out of stock': 'Немає в наявності',
    reviews: 'відгуків',
    'Brand:': 'Бренд:',
    Saved: 'Збережено',
    Save: 'Зберегти',
    'Marketplace seller': 'Продавець маркетплейсу',
    Ukraine: 'Україна',
    Specifications: 'Характеристики',
    'Customer reviews': 'Відгуки покупців',
    'Similar items': 'Схожі товари',
    'Welcome back': 'З поверненням',
    'Email is required': 'Вкажіть електронну пошту',
    'Password is required': 'Вкажіть пароль',
    'Login failed. Please check your credentials.': 'Не вдалося увійти. Перевірте дані.',
    Password: 'Пароль',
    'Admin demo:': 'Демо-адміністратор:',
    'No account yet?': 'Ще не маєте облікового запису?',
    'Create one': 'Створити',
    'Create account': 'Створити обліковий запис',
    Name: 'Ім’я',
    'Name is required': 'Вкажіть ім’я',
    'Password must be at least 6 characters': 'Пароль має містити щонайменше 6 символів',
    'Registration failed. Please try again.': 'Не вдалося зареєструватися. Спробуйте ще раз.',
    'Already have an account?': 'Вже маєте обліковий запис?',
    'Searching...': 'Пошук...',
    'Results for': 'Результати пошуку за запитом',
    'No matches found. Try a broader keyword.': 'Нічого не знайдено. Спробуйте ширший запит.',
    'Page not found': 'Сторінку не знайдено',
    'The page you’re looking for doesn’t exist or was moved.': 'Сторінка не існує або її було переміщено.',
    'Back home': 'На головну',
    Orders: 'Замовлення',
    'My orders': 'Мої замовлення',
    'Order #': 'Замовлення №',
    items: 'товарів',
    'View details': 'Переглянути деталі',
    Profile: 'Профіль',
    'Please log in to view your account.': 'Увійдіть, щоб переглянути обліковий запис.',
    'Welcome,': 'Вітаємо,',
    Account: 'Обліковий запис',
    'Name:': 'Ім’я:',
    'Email:': 'Електронна пошта:',
    'Role:': 'Роль:',
    'Quick actions': 'Швидкі дії',
    'Admin panel': 'Панель адміністратора',
    'Let’s talk tech and support.': 'Маєте запитання? Ми допоможемо.',
    Office: 'Офіс',
    Message: 'Повідомлення',
    'Send message': 'Надіслати повідомлення',
    'Message sent successfully!': 'Повідомлення успішно надіслано!',
    'We build a smarter digital shopping experience.': 'Ми створюємо зручніший досвід онлайн-покупок.',
    'MarketHub connects buyers with premium devices, accessories, and everyday tech essentials in a clean, modern marketplace designed for speed and trust.': 'MarketHub об’єднує покупців і продавців техніки та аксесуарів на сучасному маркетплейсі, де цінують швидкість і довіру.',
    'products in stock': 'товарів у наявності',
    'Curated tech': 'Добірна техніка',
    'Every product is selected for real daily value, not noise or hype.': 'Ми обираємо товари за їхньою реальною користю, а не гучною рекламою.',
    'Transparent pricing': 'Прозорі ціни',
    'Clear offers, no hidden fees, and honest product details from the start.': 'Зрозумілі пропозиції, жодних прихованих платежів і чесні описи товарів.',
    'Fast support': 'Швидка підтримка',
    'Real people help with delivery, setup, and product questions, fast.': 'Наша команда швидко допоможе з доставкою, налаштуванням і вибором товару.',
    'Marketplace feedback': 'Відгуки про маркетплейс',
    'Rate your experience': 'Оцініть свій досвід',
    rating: 'оцінка',
    ratings: 'оцінок',
    'Current average': 'Середня оцінка',
    '5 stars': '5 зірок',
    '4 stars': '4 зірки',
    '3 stars': '3 зірки',
    '2 stars': '2 зірки',
    '1 star': '1 зірка',
    Comment: 'Коментар',
    'Share a note about your marketplace experience': 'Поділіться враженнями про маркетплейс',
    'Update rating': 'Оновити оцінку',
    'Submit rating': 'Надіслати оцінку',
    'Your rating has been saved.': 'Вашу оцінку збережено.',
    'Log in': 'Увійти',
    'to leave a marketplace rating.': 'щоб оцінити маркетплейс.',
    'This field is required': 'Це поле обов’язкове',
    'Order placed successfully': 'Замовлення успішно оформлено',
    'Seller workspace': 'Кабінет продавця',
    listings: 'оголошень',
    'Sign in to list products': 'Увійдіть, щоб розміщувати товари',
    'Edit listing': 'Редагувати оголошення',
    'Add a product': 'Додати товар',
    'Product name': 'Назва товару',
    'Select category': 'Оберіть категорію',
    'Price (UAH)': 'Ціна (грн)',
    Stock: 'Кількість',
    'Image URL': 'Посилання на зображення',
    Description: 'Опис',
    'Save changes': 'Зберегти зміни',
    'Publish product': 'Опублікувати товар',
    Cancel: 'Скасувати',
    'Your listings': 'Ваші оголошення',
    Edit: 'Редагувати',
    Delete: 'Видалити',
    'You have not listed any products yet.': 'Ви ще не додали жодного товару.',
    'Choose a category before saving.': 'Оберіть категорію перед збереженням.',
    'in stock': 'у наявності',
    'MarketHub control': 'Керування MarketHub',
    Administrator: 'Адміністратор',
    Overview: 'Огляд',
    Users: 'Користувачі',
    Sellers: 'Продавці',
    Products: 'Товари',
    Reviews: 'Відгуки',
    Statistics: 'Статистика',
    Actions: 'Дії',
    'No records yet.': 'Записів поки немає.',
    'Marketplace activity at a glance. Choose a section to manage its records.': 'Огляд активності маркетплейсу. Оберіть розділ для керування записами.',
    'Marketplace rating': 'Оцінка маркетплейсу',
    'Completed order value': 'Сума виконаних замовлень',
    'Products in stock': 'Товари в наявності',
    'Seller name': 'Ім’я продавця',
    Location: 'Місто',
    'Add seller': 'Додати продавця',
    'marketplace listings': 'товарів на маркетплейсі',
    'Add product': 'Додати товар',
    Product: 'Товар',
    Slug: 'Ідентифікатор',
    'Category name': 'Назва категорії',
    'Category slug': 'Ідентифікатор категорії',
    Icon: 'Іконка',
    'Add category': 'Додати категорію',
    Order: 'Замовлення',
    Customer: 'Покупець',
    Seller: 'Продавець',
    Status: 'Статус',
    Type: 'Тип',
    Author: 'Автор',
    Review: 'Відгук',
    'Rating only': 'Лише оцінка',
    'Create product': 'Створити товар',
    'Live local data': 'Поточні локальні дані',
    management: 'керування',
    'Admin sections': 'Розділи адміністратора',
    'customer': 'покупець',
    'seller': 'продавець',
    'admin': 'адміністратор',
    Revenue: 'Дохід',
    Marketplace: 'Маркетплейс',
    Memory: 'Пам’ять',
    RAM: 'Оперативна пам’ять',
    Display: 'Дисплей',
    Camera: 'Камера',
    Battery: 'Акумулятор',
    'Operating system': 'Операційна система',
    CPU: 'Процесор',
    SSD: 'SSD',
    GPU: 'Відеокарта',
    Resolution: 'Роздільна здатність',
    Interface: 'Інтерфейс',
    Power: 'Потужність',
    Color: 'Колір',
    Sensor: 'Сенсор',
    Buttons: 'Кнопки',
    Weight: 'Вага',
    Connection: 'Підключення',
    Size: 'Розмір',
    'Refresh rate': 'Частота оновлення',
    Panel: 'Тип матриці',
    Capacity: 'Обсяг',
    Speed: 'Швидкість',
    Format: 'Формат',
    Kit: 'Комплект',
    'Read speed': 'Швидкість читання',
    Layout: 'Розкладка',
    Switches: 'Перемикачі',
    Lighting: 'Підсвічування',
    Bestseller: 'Лідер продажів',
    Popular: 'Популярне',
    Gaming: 'Ігровий',
    Business: 'Для бізнесу',
    Creator: 'Для творчості',
    'Hot Deal': 'Гаряча пропозиція',
    Value: 'Вигідна пропозиція',
    'Top Rated': 'Найвища оцінка',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = window.localStorage.getItem('markethub-language')
    return savedLanguage === 'uk' ? 'uk' : 'en'
  })

  useEffect(() => {
    window.localStorage.setItem('markethub-language', language)
    document.documentElement.lang = language === 'uk' ? 'uk' : 'en-US'
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (text) => translations[language][text] || text,
    formatCurrency: (amount) => new Intl.NumberFormat(language === 'uk' ? 'uk-UA' : 'en-US', {
      style: 'currency',
      currency: 'UAH',
      maximumFractionDigits: 0,
    }).format(amount),
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}